## Ques 1 = Write a Python Program to Add Two Matrices?

In [2]:
# Inport numpy as np
import numpy as np

# Create First Matrix
a = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
# Create Second Matrix
b = np.array([[4,5,3],
             [7,2,1],
             [9,8,6]])

print("Printing Elements of First Matrix")
print(a)
print("Printing Elements of Second Matrix")
print(b)

# Add Two Matrix
print("Addition of Two Matrix")
print(np.add(a,b))

Printing Elements of First Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Printing Elements of Second Matrix
[[4 5 3]
 [7 2 1]
 [9 8 6]]
Addition of Two Matrix
[[ 5  7  6]
 [11  7  7]
 [16 16 15]]


-------

## Ques 2 = Write a Python Program to Multiply Two Matrices?

In [9]:
#Import Numpy as np
import numpy as np

# Create First Matrix
A = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

# Create Second Matrix
B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("Print Element Of First Matrix")
print(A)
print("Printing Element of Second Matrix")
print(B)

# Multiply of Two Matrix
print("Multiply of Two Matrix")
print(A*B)


Print Element Of First Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Printing Element of Second Matrix
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Multiply of Two Matrix
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


----------

## Ques 3 = Write a Python Program to Transpose a Matrix?

In [10]:
# Import Numpy as np
import numpy as np

# Create A Matrix
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print(f"Matrix is : {a}")

a = np.transpose(a)
print(f"\n Transposed Matrix is : ")
print(a)

Matrix is : [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

 Transposed Matrix is : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


--------

## Ques 4 = Write a Python Program to Sort Words in Alphabetic Order?

In [37]:
import numpy as np

# define a with input
a = ['Anand','Raghav','Mayur','Harish','Sandeep']
print(f"unsorted Words are : {a}")

sort = np.sort(a)

#Print the Result for Users
print(f"Sorted Words in Alphabetic Order :")
print(sort)

unsorted Words are : ['Anand', 'Raghav', 'Mayur', 'Harish', 'Sandeep']
Sorted Words in Alphabetic Order :
['Anand' 'Harish' 'Mayur' 'Raghav' 'Sandeep']


---------

## Ques 5 = Write a Python Program to Remove Punctuation From a String?

In [39]:
# Declear a String
str = "My @name : is & Anand: Soni."
# Print THe str 
print(F"The original String is : {str}")

# define punctuation
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

for ele in str:
    if ele in punc:
        str = str.replace(ele, "")
        
# display the unpunctuated string
print(f"\nThe String after Punctuation Removal is : {str}")

The original String is : My @name : is & Anand: Soni.

The String after Punctuation Removal is : My name  is  Anand Soni


--------

                                                                        END